server:
  port: 8980
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping_c
    username: root
    password: 123
  servlet:
    multipart:
      max-file-size: 1000MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.shopping.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logistic:
  logisticApi: "http://sandboxapi.kdniao.com:8080/kdniaosandbox/gateway/exterfaceInvoke.json"
  EBusinessID: "test1761737"
  ApiKey: "e6b20e99-2ae9-47aa-a3ab-1914d48f9f96"

natapp: "http://i55j6s.natappfree.cc"